name: MHSA_LSTM
main_model_class: MHSARecDuoModel
params:
    mhsa_model_params:
        n_features: 1024
        query_dims: 
        key_dims: 
        n_heads: 1
        p: 0.1
    rec_model_params:
        rec_model_kwargs:
            lstm:
                input_size: 
                hidden_size: 1024
                num_layers: 1
                batch_first: True
                dropout: 0.1
                bidirectional: False
        hidden_layers: []
        p: 0.
    hidden_layers: [512, 128, 64]
    p: 0.1
training_configs:
    n_epochs: 1
    batch_size: 1024
    loss_function: CrossEntropyLoss
    optimizer: Adam
    learning_rate: 0.00001
    random_state: 42
    scheduler: 
    scheduler_params:
    use_callback: True
    eval_steps: 200
    eval_batch_size: 1024
    overwrite_existing_callback: True
    checkpoint_each_epoch: True
    metrics_names:
        - accuracy
        - balanced_accuracy
        - precision
        - recall
        - f1
callback_logdir: callback_head_model_MHSA_LSTM