path:
    path_to_preprocessed_data: data/preprocessed
    path_to_tokenized_data: data/tokenized
    path_to_encoded_data: data/encoded
    path_to_target_data: data/target
    path_to_models: models
    path_to_params: src/params
    path_to_logits: data/logits
    path_to_logs: logs
    path_to_predictions: data/predictions
data_tokenization:
    max_length: 16
    model_checkpoint: ai-forever/rugpt3medium_based_on_gpt2
data_encoding:
    n_labels: 2
    batch_size: 512
    n_batches_per_save: 100
    start_batch: 
    end_batch: 
    model_checkpoint: ai-forever/rugpt3medium_based_on_gpt2
head_model_training:
    embedding_file_size: 51200
    validation_embedding_id: 1
    min_train_embedding_id: 2
    max_train_embedding_id: 85
    training_configs:
        n_epochs: 1
        batch_size: 1024
        loss_function: CrossEntropyLoss
        optimizer: Adam
        learning_rate: 0.00001
        random_state: 42
        scheduler: 
        scheduler_params:
        use_callback: True
        eval_steps: 200
        eval_batch_size: 1024
        overwrite_existing_callback: True
        checkpoint_each_epoch: True
        metrics_names:
            - accuracy
            - balanced_accuracy
            - precision
            - recall
            - f1
head_model_fold_training:
    embedding_file_size: 51200
    validation_embedding_id: 1
    min_train_embedding_id: 2
    max_train_embedding_id: 85
    training_configs:
        n_epochs: 3
        batch_size: 1024
        loss_function: CrossEntropyLoss
        optimizer: Adam
        learning_rate: 0.00001
        random_state: 42
        scheduler: 
        scheduler_params:
        use_callback: True
        overwrite_existing_callback: True
        checkpoint_each_epoch: True
        metrics_names:
            - accuracy
            - balanced_accuracy
            - precision
            - recall
            - f1
    folds_ids_range:
        - [2, 22]
        - [23, 43]
        - [44, 64]
        - [65, 85]
stacking_model_training:
    embedding_file_size: 51200
    min_train_embedding_id: 2
    max_train_embedding_id: 85
    head_models: 
        - MHSA_STCNN_GRU
        - MHSA_STCNN_BiRNN
        - MHSA_STCNN_BiLSTM
    models:
        - LogisticRegression
        - RandomForestClassifier
        - rbfSVC
        - LinearSVC
        - XGBClassifier
        - LGBMClassifier
    scoring_metric: f1
    swap_labels: True
    n_folds: 4
    n_jobs: -1
    random_state: 42
    optimization_direction: maximize
    n_trials: 100
predicting:
    embedding_file_size: 51200
    embedding_ids: [0]
    head_models:
        - head_model_FINAL_MHSA_STCNN_BiRNN
        - head_model_FINAL_MHSA_STCNN_BiLSTM
        - head_model_FINAL_MHSA_STCNN_GRU
    second_level_model: LGBMClassifier
    metrics_names:
        - accuracy
        - balanced_accuracy
        - precision
        - recall
        - f1